[package]
name = "infinite-five"
version = "0.5.2"
description = "Infinite Five cross-platform shell"
authors = ["StanleyLl0yd"]
edition = "2021"

[lib]
name = "infinite_five_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = "=2.6.3"

[dependencies]
tauri = "=2.11.3"
