[package]
name = "infinite-five"
version = "0.6.3"
description = "Infinite Five cross-platform shell"
authors = ["StanleyLl0yd"]
edition = "2021"

[lib]
name = "infinite_five_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = "=2.6.3"

[dependencies]
infinite-five-game-core = { path = "../crates/game-core" }
tauri = "=2.11.3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false
